# Generated by Django 4.1.7 on 2023-04-12 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='artice',
            new_name='article',
        ),
    ]
