# Generated by Django 4.1.7 on 2023-04-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='branch',
            field=models.CharField(default='1 branch', max_length=256, unique=True),
        ),
    ]
