# Generated by Django 4.1.7 on 2023-04-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shop_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='branch',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
